import './globals.css'
import { Inter } from 'next/font/google'
import Header from '../components/Header'
import Footer from '@/components/Footer';
import React from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'FitDock',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

   
  return (
    <html lang="en">
      <body className={inter.className}>
      
        {children}
  
      </body>
    </html>
  )
}
